import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
          "error-container": "#ffdad6",
          "primary": "#ab3600",
          "on-secondary-fixed": "#191e00",
          "secondary-fixed-dim": "#b8d300",
          "on-tertiary-fixed": "#1c1b1b",
          "on-surface-variant": "#5b4138",
          "surface-container-high": "#eae8e6",
          "on-tertiary-container": "#2c2c2c",
          "inverse-primary": "#ffb59c",
          "outline-variant": "#e3bfb3",
          "tertiary-fixed": "#e5e2e1",
          "tertiary-fixed-dim": "#c8c6c5",
          "secondary-fixed": "#d2f000",
          "surface-container-lowest": "#ffffff",
          "surface-dim": "#dbdad8",
          "outline": "#8f7066",
          "secondary-container": "#d0ed00",
          "error": "#ba1a1a",
          "surface-container": "#efedec",
          "surface-bright": "#fbf9f7",
          "on-surface": "#1b1c1b",
          "surface-container-highest": "#e4e2e0",
          "inverse-surface": "#30302f",
          "on-error-container": "#93000a",
          "on-secondary": "#ffffff",
          "surface-container-low": "#f5f3f1",
          "tertiary": "#5f5e5e",
          "primary-fixed": "#ffdbcf",
          "on-primary": "#ffffff",
          "on-tertiary-fixed-variant": "#474746",
          "primary-container": "#ff5f1f",
          "primary-fixed-dim": "#ffb59c",
          "on-primary-container": "#561700",
          "tertiary-container": "#959393",
          "on-background": "#1b1c1b",
          "secondary": "#576500",
          "surface": "#fbf9f7",
          "on-secondary-container": "#5b6900",
          "surface-tint": "#ab3600",
          "on-error": "#ffffff",
          "on-primary-fixed-variant": "#832700",
          "on-tertiary": "#ffffff",
          "on-primary-fixed": "#390c00",
          "surface-variant": "#e4e2e0",
          "inverse-on-surface": "#f2f0ee",
          "on-secondary-fixed-variant": "#414c00",
          "background": "#fbf9f7",
          "high-gloss-lime": "#dfff00",
          "warm-off-white": "#fbf9f7",
          "ink-black": "#1b1c1b",
          "neon-coral": "#ff5f1f",
          "surface-border": "#e5e5e5",
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px",
          "2xl": "1rem",
          "3xl": "1.5rem"
      },
      "spacing": {
          "stack-md": "32px",
          "stack-lg": "48px",
          "stack-xl": "72px",
          "stack-sm": "16px",
          "margin-mobile": "20px",
          "gutter": "24px",
          "container-max": "1280px",
          "margin-desktop": "64px",
          "unit": "8px",
          "section-gap": "96px",
          "base": "8px"
      },
      "fontFamily": {
          "display-lg": ["var(--font-bricolage)", "sans-serif"],
          "body-md": ["var(--font-hanken)", "sans-serif"],
          "headline-lg": ["var(--font-bricolage)", "sans-serif"],
          "body-lg": ["var(--font-hanken)", "sans-serif"],
          "headline-lg-mobile": ["var(--font-bricolage)", "sans-serif"],
          "label-caps": ["var(--font-jetbrains)", "monospace"],
          "headline-md": ["var(--font-bricolage)", "sans-serif"],
          "display-xl-mobile": ["var(--font-bricolage)", "sans-serif"],
          "display-xl": ["var(--font-bricolage)", "sans-serif"],
          "label-mono": ["var(--font-jetbrains)", "monospace"]
      },
      "fontSize": {
          "display-lg": ["48px", { "lineHeight": "1.12", "letterSpacing": "0", "fontWeight": "800" }],
          "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-lg": ["36px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "700" }],
          "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
          "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "0", "fontWeight": "700" }],
          "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
          "headline-md": ["26px", { "lineHeight": "1.25", "letterSpacing": "0", "fontWeight": "700" }],
          "display-xl-mobile": ["38px", {lineHeight: "44px", letterSpacing: "0", fontWeight: "800"}], 
          "display-xl": ["52px", {lineHeight: "58px", letterSpacing: "0", fontWeight: "800"}],
          "label-mono": ["14px", {lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500"}]
      },
      "boxShadow": {
          "glass": "0 8px 32px 0 rgba(171, 54, 0, 0.08)",
          "glossy-layer": "0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 10px 24px -5px rgba(171, 54, 0, 0.1)",
          "inner-light": "inset 0 1px 0 0 rgba(255, 255, 255, 0.6)"
      }
    }
  }
} satisfies Config;
